name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5'
          channel: 'stable'
          cache: true

      - name: Delete stale generated plugin files
        run: |
          rm -f mobile_app/.flutter-plugins
          rm -f mobile_app/.flutter-plugins-dependencies

      - name: Get dependencies
        run: |
          cd mobile_app
          flutter clean
          flutter pub get

      - name: Setup permanent debug keystore
        run: |
          mkdir -p ~/.android
          cp mobile_app/android/app/debug.keystore ~/.android/debug.keystore

      - name: Build APK
        run: |
          cd mobile_app
          flutter build apk --release --no-shrink -v
        env:
          GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.parallel=false -Dkotlin.incremental=false"
          ORG_GRADLE_PROJECT_org_gradle_java_installations_auto_detect: false
          ORG_GRADLE_PROJECT_org_gradle_java_installations_fromEnv: JAVA_HOME

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: mobile_app/build/app/outputs/flutter-apk/app-release.apk
